export const REFINED_GRAINS = [
  'white rice',
  'white bread',
  'white pasta',
  'maida',
  'refined flour',
  'white roti',
] as const;

export const LEAN_PROTEINS = [
  'chicken breast',
  'fish',
  'turkey',
  'eggs',
  'tofu',
  'paneer',
  'dal',
  'lentils',
  'beans',
  'chickpeas',
  'soy chunks',
  'sprouts',
  'nuts',
  'seeds',
] as const;

export const RED_MEATS = [
  'mutton',
  'lamb',
  'goat',
  'beef',
  'pork',
] as const;

export const PROCESSED_MEATS = [
  'bacon',
  'sausage',
  'ham',
  'salumi',
] as const;

export const HEALTHY_OILS = [
  'olive oil',
  'canola oil',
  'soybean oil',
  'corn oil',
  'sunflower oil',
  'peanut oil',
  'mustard oil',
  'ghee',
] as const;

export const UNHEALTHY_FATS = [
  'partially hydrogenated oil',
  'trans fat',
  'vanaspati',
  'margarine',
] as const;

export const HEALTH_TIPS: HealthTip[] = [
  {
    id: 'plate-balance',
    title: 'Build a Balanced Plate',
    body: 'Fill half your plate with vegetables and fruits, a quarter with whole grains, and a quarter with healthy protein. This naturally controls portions and ensures nutrient variety.',
    icon: '🍽️',
    category: 'general',
  },
  {
    id: 'color-variety',
    title: 'Eat the Rainbow',
    body: 'Different colored fruits and vegetables provide different nutrients. Aim for at least 3 different colors on your plate — dark leafy greens, red bell peppers, orange carrots, purple cabbage, etc.',
    icon: '🌈',
    category: 'veg-fruit',
  },
  {
    id: 'whole-grains',
    title: 'Go Whole Grain',
    body: 'Whole grains like brown rice, oats, quinoa, and whole wheat keep your blood sugar steady and provide fiber, B vitamins, and minerals. Swap refined grains (white rice, maida) for whole grain versions.',
    icon: '🌾',
    category: 'whole-grain',
  },
  {
    id: 'protein-quality',
    title: 'Protein Package Matters',
    body: 'What comes with your protein matters. Fish, poultry, beans, and nuts bring healthy fats and fiber. Limit red meat and avoid processed meats like bacon and sausage.',
    icon: '🥩',
    category: 'protein',
  },
  {
    id: 'healthy-fats',
    title: 'Choose Healthy Fats',
    body: 'Not all fat is bad. Olive, canola, sunflower, and mustard oils are heart-healthy. Avoid trans fats and partially hydrogenated oils. Remember: low-fat doesn\'t mean healthy.',
    icon: '🫒',
    category: 'fats',
  },
  {
    id: 'skip-sugary-drinks',
    title: 'Skip Sugary Drinks',
    body: 'Sugary beverages are a major source of empty calories. Drink water, coffee, or tea instead. Limit juice to one small glass per day and dairy to 1-2 servings.',
    icon: '🥤',
    category: 'beverages',
  },
  {
    id: 'fiber-benefits',
    title: 'Fiber is Your Friend',
    body: 'Fiber slows digestion, keeps blood sugar steady, lowers cholesterol, and helps prevent constipation. Get it from whole grains, legumes, vegetables, and fruits.',
    icon: '🫘',
    category: 'fiber',
  },
  {
    id: 'protein-amount',
    title: 'How Much Protein?',
    body: 'Most adults need about 0.8g of protein per kg of body weight. For a 140lb person, that\'s ~50g/day. Spread protein across meals rather than loading up at one meal.',
    icon: '🥚',
    category: 'protein',
  },
  {
    id: 'watch-sodium',
    title: 'Watch Hidden Sodium',
    body: 'Too much sodium raises blood pressure. Processed foods, restaurant meals, and packaged snacks are the biggest sources. Season with herbs and spices instead of salt.',
    icon: '🧂',
    category: 'sodium',
  },
  {
    id: 'smart-swaps',
    title: 'Simple Healthy Swaps',
    body: 'Replace white rice with brown rice or quinoa. Choose whole wheat roti instead of naan. Snack on nuts and fruit instead of fried snacks. Drink water instead of soda.',
    icon: '🔄',
    category: 'general',
  },
  {
    id: 'portion-control',
    title: 'Portion Awareness',
    body: 'Even healthy foods can lead to weight gain in large portions. Use the plate method: ½ veg/fruit, ¼ whole grains, ¼ protein to keep portions balanced naturally.',
    icon: '✋',
    category: 'general',
  },
  {
    id: 'vegetables-first',
    title: 'Eat Vegetables First',
    body: 'Eating vegetables first at a meal can help control blood sugar spikes and make you feel fuller. Start meals with a salad or vegetable-based soup.',
    icon: '🥗',
    category: 'veg-fruit',
  },
  {
    id: 'limit-red-meat',
    title: 'Limit Red Meat',
    body: 'High consumption of red meat is linked to increased risk of heart disease and certain cancers. Try to have red meat only occasionally, and choose lean cuts when you do.',
    icon: '🥩',
    category: 'protein',
  },
  {
    id: 'stay-hydrated',
    title: 'Stay Hydrated Right',
    body: 'Water is the best choice. Coffee and tea are fine in moderation. Skip sugary sodas, packaged juices, and energy drinks — they add calories without nutrition.',
    icon: '💧',
    category: 'beverages',
  },
  {
    id: 'whole-grain-kernel',
    title: 'The Whole Grain Kernel',
    body: 'The bran provides fiber and B vitamins, the germ has healthy fats and vitamin E, and the endosperm has carbs and protein. Refined grains strip away the bran and germ, losing most nutrients.',
    icon: '🌾',
    category: 'whole-grain',
  },
  {
    id: 'read-labels',
    title: 'Reading Food Labels',
    body: 'Look for whole grain as the first ingredient. Check the carbohydrate-to-fiber ratio — aim for less than 10:1. Watch for hidden sugars and sodium in packaged foods.',
    icon: '🏷️',
    category: 'general',
  },
  {
    id: 'diet-quality',
    title: 'Focus on Diet Quality',
    body: 'The overall quality of your diet matters more than any single nutrient. A pattern of whole foods — vegetables, fruits, whole grains, healthy proteins — beats counting calories.',
    icon: '⭐',
    category: 'general',
  },
];

export interface HealthTip {
  id: string;
  title: string;
  body: string;
  icon: string;
  category: 'general' | 'veg-fruit' | 'whole-grain' | 'protein' | 'fats' | 'beverages' | 'fiber' | 'sodium';
}

export const VITAMIN_RDA: Record<string, { women?: string; men?: string; upperLimit?: string }> = {
  'Vitamin A': { women: '700 mcg (2,333 IU)', men: '900 mcg (3,000 IU)', upperLimit: '3,000 mcg (10,000 IU)' },
  'Vitamin C': { women: '75 mg', men: '90 mg', upperLimit: '2,000 mg' },
  'Vitamin D': { women: '15 mcg (600 IU)', men: '15 mcg (600 IU)', upperLimit: '100 mcg (4,000 IU)' },
  'Vitamin E': { women: '15 mg', men: '15 mg', upperLimit: '1,000 mg' },
  'Vitamin B12': { women: '2.4 mcg', men: '2.4 mcg' },
  Folate: { women: '400 mcg', men: '400 mcg', upperLimit: '1,000 mcg' },
  Iron: { women: '18 mg', men: '8 mg', upperLimit: '45 mg' },
  Calcium: { women: '1,000 mg', men: '1,000 mg', upperLimit: '2,500 mg' },
  Magnesium: { women: '310-320 mg', men: '400-420 mg', upperLimit: '350 mg (supplements only)' },
  Potassium: { women: '2,600 mg', men: '3,400 mg' },
  Sodium: { women: '1,500 mg', men: '1,500 mg' },
  Zinc: { women: '8 mg', men: '11 mg', upperLimit: '40 mg' },
};

export const DISH_HEALTH_MAP: Record<string, { healthCategories: string[]; tags: string[] }> = {
  'aloo-paratha': {
    healthCategories: ['whole-grain', 'fried'],
    tags: ['high-carb', 'high-fat', 'low-protein'],
  },
  'bedmi-puri': {
    healthCategories: ['refined-grain', 'fried'],
    tags: ['high-carb', 'high-fat', 'low-protein'],
  },
  'dal-makhani': {
    healthCategories: ['legume'],
    tags: ['high-protein', 'high-fat', 'good-fiber'],
  },
  'rogan-josh': {
    healthCategories: ['red-meat'],
    tags: ['high-protein', 'high-fat', 'high-sodium'],
  },
  'butter-chicken': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'high-fat', 'moderate'],
  },
  'samosa': {
    healthCategories: ['fried'],
    tags: ['high-carb', 'high-fat', 'low-nutrient'],
  },
  'soya-chunks-masala': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'high-fiber', 'healthy'],
  },
  'soybean-matar': {
    healthCategories: ['legume'],
    tags: ['high-protein', 'high-fiber', 'healthy'],
  },
  'tofu-tikka-masala': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'calcium', 'healthy'],
  },
  'paneer-tikka-masala': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'high-fat', 'calcium'],
  },
  'jeera-rice': {
    healthCategories: ['refined-grain'],
    tags: ['high-carb', 'low-fiber'],
  },
  'veg-manchurian': {
    healthCategories: ['fried'],
    tags: ['moderate', 'high-sodium'],
  },
  'pani-puri': {
    healthCategories: ['fried'],
    tags: ['high-carb', 'low-nutrient'],
  },
  'egg-curry-north': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'healthy'],
  },
  'egg-bhurji': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'quick'],
  },
  'masala-omelette': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'low-carb'],
  },
  'egg-fried-rice': {
    healthCategories: ['refined-grain'],
    tags: ['moderate-protein', 'high-carb'],
  },
  'malai-kofta': {
    healthCategories: ['fried'],
    tags: ['high-fat', 'high-calorie', 'indulgent'],
  },
  'paneer-butter-masala': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'high-fat', 'rich'],
  },
  'shahi-paneer': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'high-fat', 'rich'],
  },
  'kadai-paneer': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'moderate'],
  },
  'palak-paneer': {
    healthCategories: ['lean-protein', 'veg-fruit'],
    tags: ['high-protein', 'iron', 'fiber', 'healthy'],
  },
  'paneer-lababdar': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'high-fat', 'rich'],
  },
  'paneer-bhurji': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'quick'],
  },
  'mushroom-masala': {
    healthCategories: ['veg-fruit'],
    tags: ['low-calorie', 'protein', 'vitamin-d'],
  },
  'mix-veg': {
    healthCategories: ['veg-fruit'],
    tags: ['fiber', 'vitamins', 'healthy', 'low-calorie'],
  },
  'methi-aloo': {
    healthCategories: ['veg-fruit'],
    tags: ['fiber', 'iron', 'low-fat'],
  },
  'bhindi-do-pyaza': {
    healthCategories: ['veg-fruit'],
    tags: ['fiber', 'vitamin-c', 'low-calorie'],
  },
  'dal-tadka': {
    healthCategories: ['legume'],
    tags: ['high-protein', 'fiber', 'healthy'],
  },
  'chana-dal': {
    healthCategories: ['legume'],
    tags: ['high-protein', 'high-fiber', 'healthy'],
  },
  'urad-dal': {
    healthCategories: ['legume'],
    tags: ['high-protein', 'iron', 'healthy'],
  },
  'rajma-chawal': {
    healthCategories: ['legume', 'refined-grain'],
    tags: ['high-protein', 'fiber', 'balanced'],
  },
  'chole': {
    healthCategories: ['legume'],
    tags: ['high-protein', 'fiber', 'healthy'],
  },
  'chole-bhature': {
    healthCategories: ['legume', 'fried'],
    tags: ['high-protein', 'high-fat', 'indulgent'],
  },
  'veg-pulao-north': {
    healthCategories: ['refined-grain'],
    tags: ['moderate', 'aromatic'],
  },
  'dal-khichdi': {
    healthCategories: ['legume', 'whole-grain'],
    tags: ['high-protein', 'fiber', 'comfort', 'healthy'],
  },
  'veg-biryani': {
    healthCategories: ['refined-grain'],
    tags: ['moderate', 'festive'],
  },
  'lassi': {
    healthCategories: ['dairy'],
    tags: ['probiotic', 'calcium'],
  },
  'masala-chaai': {
    healthCategories: ['healthy-beverage'],
    tags: ['antioxidant', 'moderate'],
  },
  'chaas': {
    healthCategories: ['healthy-beverage'],
    tags: ['probiotic', 'low-calorie', 'healthy'],
  },
  'aamras': {
    healthCategories: ['veg-fruit'],
    tags: ['vitamin-c', 'natural-sugar'],
  },
  'paneer-tikka': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'healthy'],
  },
  'hariyali-paneer-tikka': {
    healthCategories: ['lean-protein', 'veg-fruit'],
    tags: ['high-protein', 'fiber', 'healthy'],
  },
  'malai-tikka': {
    healthCategories: ['lean-protein'],
    tags: ['high-protein', 'moderate'],
  },
  'gulab-jamun': {
    healthCategories: ['dessert'],
    tags: ['high-sugar', 'indulgent'],
  },
  'jalebi': {
    healthCategories: ['dessert'],
    tags: ['high-sugar', 'indulgent'],
  },
  'rasgulla': {
    healthCategories: ['dessert'],
    tags: ['high-sugar', 'moderate'],
  },
  'kheer': {
    healthCategories: ['dessert'],
    tags: ['moderate-sugar', 'dairy'],
  },
  'gobhi-paratha': {
    healthCategories: ['whole-grain'],
    tags: ['high-carb', 'moderate'],
  },
  'mooli-paratha': {
    healthCategories: ['whole-grain'],
    tags: ['high-carb', 'moderate'],
  },
  'dal-paratha': {
    healthCategories: ['legume', 'whole-grain'],
    tags: ['high-protein', 'high-carb'],
  },
  'methi-paratha': {
    healthCategories: ['veg-fruit', 'whole-grain'],
    tags: ['iron', 'fiber', 'moderate'],
  },
  'mix-paratha': {
    healthCategories: ['veg-fruit', 'whole-grain'],
    tags: ['moderate'],
  },
  'dahi-bhalla': {
    healthCategories: ['dairy'],
    tags: ['probiotic', 'moderate'],
  },
  'aloo-tikki': {
    healthCategories: ['fried', 'starchy-veg'],
    tags: ['high-carb', 'low-nutrient'],
  },
  'papdi-chaat': {
    healthCategories: ['fried'],
    tags: ['high-carb', 'moderate'],
  },
  'sev-poori': {
    healthCategories: ['fried'],
    tags: ['high-carb', 'moderate'],
  },
  'dahi-puri': {
    healthCategories: ['fried', 'dairy'],
    tags: ['moderate'],
  },
  'chole-tikki': {
    healthCategories: ['legume', 'fried'],
    tags: ['high-protein', 'moderate'],
  },
  'butter-naan': {
    healthCategories: ['refined-grain'],
    tags: ['high-carb', 'low-fiber'],
  },
  'tandoori-roti': {
    healthCategories: ['whole-grain'],
    tags: ['high-fiber', 'healthy', 'low-fat'],
  },
  'white-bread': {
    healthCategories: ['refined-grain'],
    tags: ['high-carb', 'low-fiber'],
  },
  'brown-bread': {
    healthCategories: ['whole-grain'],
    tags: ['fiber', 'healthy'],
  },
  'milk-bread': {
    healthCategories: ['refined-grain'],
    tags: ['high-carb', 'low-fiber'],
  },
  'avocado-sandwich': {
    healthCategories: ['healthy-fat', 'veg-fruit'],
    tags: ['healthy', 'high-fiber', 'high-protein', 'low-calorie'],
  },
  'bhakri': {
    healthCategories: ['whole-grain'],
    tags: ['high-fiber', 'healthy', 'low-fat'],
  },
  'jolada-roti': {
    healthCategories: ['whole-grain'],
    tags: ['high-fiber', 'healthy', 'low-fat'],
  },
  'methi-thepla': {
    healthCategories: ['whole-grain', 'veg-fruit'],
    tags: ['fiber', 'iron', 'healthy'],
  },
  'north-sarson-saag-makki': {
    healthCategories: ['whole-grain', 'veg-fruit'],
    tags: ['fiber', 'healthy'],
  },
  'overnight-oats': {
    healthCategories: ['whole-grain'],
    tags: ['high-fiber', 'healthy', 'low-fat'],
  },

  'achari-baingan': { healthCategories: ["veg-fruit"], tags: ["fiber"] },
  'almond-flour-peanut-butter-cookies': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'aloo-baingan': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'aloo-bhaja': { healthCategories: ["veg-fruit","fried"], tags: ["fiber","low-calorie","high-fat"] },
  'aloo-matar': { healthCategories: ["veg-fruit"], tags: ["fiber"] },
  'aloo-methi': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie","iron","healthy"] },
  'aloo-palak': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins","low-calorie","iron","healthy"] },
  'aloo-tamatar': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins","low-calorie"] },
  'american-chop-suey': { healthCategories: ["refined-grain","fried"], tags: ["high-carb","high-fat","fiber"] },
  'andhra-prawn-masala-2': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'appam-stew': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'apple-walnut-salad': { healthCategories: ["veg-fruit","healthy-fat"], tags: ["fiber","low-calorie","healthy"] },
  'arugula-smoothie': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'arunachal-thukpa-veg': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'assam-masor-tenga': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber","low-calorie"] },
  'aubergine-curry': { healthCategories: ["legume","veg-fruit"], tags: ["high-protein","fiber"] },
  'avocado-green-goddess-dressing': { healthCategories: ["veg-fruit","healthy-fat"], tags: ["fiber","low-calorie"] },
  'avocado-peanut-butter-smoothie': { healthCategories: ["sugary-beverage"], tags: ["healthy","high-protein"] },
  'badam-shorba': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'bafla-gravy': { healthCategories: ["refined-grain","legume"], tags: ["high-carb","high-calorie","high-protein","fiber"] },
  'baingan-masala': { healthCategories: ["veg-fruit"], tags: ["fiber"] },
  'bajre-ka-raab': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'baked-penne-roasted-veg': { healthCategories: ["refined-grain","veg-fruit"], tags: ["high-carb","fiber"] },
  'banana-bread-no-brown-sugar': { healthCategories: ["refined-grain"], tags: ["high-carb","fiber","healthy"] },
  'banana-bread-no-butter': { healthCategories: ["refined-grain","unhealthy-fat"], tags: ["high-carb","high-fat","fiber","healthy"] },
  'banana-peanut-butter-sandwich': { healthCategories: ["refined-grain","lean-protein","healthy-fat"], tags: ["high-carb","high-protein","healthy","low-calorie"] },
  'banana-pudding-lasagna': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'banana-smoothie-bowl': { healthCategories: ["sugary-beverage"], tags: ["high-protein","low-calorie"] },
  'bbq-jackfruit-burrito-bowl': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein","fiber"] },
  'bean-stew-brown-rice': { healthCategories: ["refined-grain","legume"], tags: ["high-carb","high-protein","fiber"] },
  'beetroot-feta-salad': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie","iron"] },
  'besan-mix-veg': { healthCategories: ["veg-fruit","fried"], tags: ["fiber","low-calorie","high-fat"] },
  'besan_chilla_curry_north': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'besan_chilla_north': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein","low-calorie"] },
  'birthday-cake-muffins': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'biscoff-donuts': { healthCategories: ["dessert"], tags: ["high-sugar","indulgent"] },
  'blueberry-banana-blast-smoothie': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'blueberry-banana-oat-bread': { healthCategories: ["whole-grain","veg-fruit"], tags: ["high-fiber","fiber"] },
  'bombay-grill-sandwich': { healthCategories: ["refined-grain"], tags: ["high-carb","low-calorie"] },
  'breakfast-fruit-salad': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins","low-calorie"] },
  'butter-chicken-wala': { healthCategories: ["lean-protein","unhealthy-fat"], tags: ["high-protein","high-fat","high-calorie"] },
  'california-grape-avocado-salad': { healthCategories: ["veg-fruit","healthy-fat"], tags: ["fiber","low-calorie"] },
  'chana-masala': { healthCategories: ["legume"], tags: ["high-protein","fiber"] },
  'chana-sattu-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'cherry-almond-chocolate-cookies': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'chicken-65': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat","low-calorie"] },
  'chicken-biryani': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-calorie","high-protein"] },
  'chicken-lollipop': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat"] },
  'chicken-malai-tikka': { healthCategories: ["lean-protein","unhealthy-fat"], tags: ["high-protein","high-fat","low-calorie"] },
  'chicken-manchurian': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat"] },
  'chicken-tikka': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'chicken-tikka-masala-2': { healthCategories: ["lean-protein"], tags: ["high-protein","high-calorie"] },
  'chickpea-lentil-saute-apple-curry': { healthCategories: ["legume"], tags: ["high-protein","fiber"] },
  'chickpea-tikka-masala': { healthCategories: ["legume"], tags: ["high-protein","fiber"] },
  'chilli-chicken': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'chilli-garlic-fried-rice': { healthCategories: ["refined-grain","fried"], tags: ["high-carb","high-fat"] },
  'chilli-mushroom': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber"] },
  'chocolate-donuts': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'chocolate-milk-tea': { healthCategories: ["dessert"], tags: ["high-sugar","calcium"] },
  'chow-mein': { healthCategories: ["refined-grain"], tags: ["high-carb"] },
  'classic-pancakes': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'coconut-milkshake': { healthCategories: ["sugary-beverage","dairy"], tags: ["healthy"] },
  'coconut-veg-stew': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'corn-masala': { healthCategories: ["veg-fruit"], tags: ["fiber"] },
  'cottage-cheese-fruit': { healthCategories: ["lean-protein","veg-fruit","unhealthy-fat"], tags: ["high-protein","fiber","low-calorie","high-fat","calcium"] },
  'crispy-potato-tacos': { healthCategories: ["veg-fruit","fried"], tags: ["fiber","high-fat"] },
  'curried-sweet-potato-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'dahi-tadka-oats': { healthCategories: ["whole-grain"], tags: ["high-fiber","low-calorie","fiber","healthy"] },
  'dal-baati': { healthCategories: ["refined-grain","legume"], tags: ["high-carb","high-calorie","high-protein","fiber"] },
  'dal-dhokli': { healthCategories: ["legume"], tags: ["high-protein","fiber","high-calorie"] },
  'dal-fry': { healthCategories: ["legume","fried"], tags: ["high-protein","fiber","high-fat"] },
  'dal-gosht': { healthCategories: ["legume","unhealthy-fat"], tags: ["high-protein","fiber","high-fat","high-calorie"] },
  'dal-makhni-wala': { healthCategories: ["legume"], tags: ["high-protein","fiber","high-calorie"] },
  'dal-palak': { healthCategories: ["legume","veg-fruit"], tags: ["high-protein","fiber","iron","healthy"] },
  'dal-panchmel-shorba': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'dal-poha': { healthCategories: ["refined-grain","legume"], tags: ["high-carb","high-protein","fiber"] },
  'dal-puri': { healthCategories: ["refined-grain","legume","fried"], tags: ["high-carb","high-protein","fiber","high-fat"] },
  'dal_rice_chilla_east': { healthCategories: ["refined-grain","legume"], tags: ["high-carb","high-protein","fiber","probiotic"] },
  'dalimbo': { healthCategories: ["legume","fried"], tags: ["high-protein","fiber","high-fat"] },
  'dim-er-torkaari': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber","low-calorie"] },
  'dragon-fruit-smoothie': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'dum-aloo': { healthCategories: ["veg-fruit","unhealthy-fat"], tags: ["fiber","high-fat"] },
  'eggless-brownies': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'english-muffin-pizzas': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'falooda': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'flourless-gluten-free-brownies': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'gahat-ka-shorba': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'gajar-ka-halwa': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'galouti-kebab': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat","low-calorie"] },
  'garlic-bread-grilled-cheese': { healthCategories: ["refined-grain","lean-protein","veg-fruit","unhealthy-fat"], tags: ["high-carb","high-protein","fiber","high-fat"] },
  'garlic-chicken': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'ginger-carrot-coconut-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'gobi-manchurian': { healthCategories: ["veg-fruit","fried"], tags: ["fiber","high-fat"] },
  'gobi-matar': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins","low-calorie"] },
  'goose-dum-biryani': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-calorie","high-protein"] },
  'greek-nachos-baked-chickpeas': { healthCategories: ["legume"], tags: ["high-protein","fiber"] },
  'green-smoothie': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'grilled-pineapple': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins","low-calorie","healthy"] },
  'gujarati-dal': { healthCategories: ["legume"], tags: ["high-protein","fiber"] },
  'hakka-noodles': { healthCategories: ["refined-grain"], tags: ["high-carb"] },
  'healthy-hot-chocolate': { healthCategories: ["dessert"], tags: ["high-sugar","calcium"] },
  'healthy-oatmeal-banana-pancakes': { healthCategories: ["whole-grain","lean-protein"], tags: ["high-fiber","high-protein"] },
  'healthy-pumpkin-smoothie': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'high-protein-veggie-burgers': { healthCategories: ["refined-grain","lean-protein","veg-fruit"], tags: ["high-carb","high-protein","fiber"] },
  'honey-chilli-potato': { healthCategories: ["veg-fruit","fried"], tags: ["fiber","high-fat"] },
  'honeydew-milk-tea': { healthCategories: ["healthy-beverage","dairy"], tags: ["antioxidant","low-calorie"] },
  'hot-and-sour-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'hot-garlic-sauce-veg': { healthCategories: ["veg-fruit"], tags: ["fiber"] },
  'idiyappam': { healthCategories: ["refined-grain"], tags: ["high-carb","low-calorie"] },
  'indian-asparagus-lemon-cumin': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'indian-fried-rice-khichdi': { healthCategories: ["refined-grain","legume","fried"], tags: ["high-carb","high-protein","fiber","high-fat"] },
  'kadhi-khakra': { healthCategories: ["legume"], tags: ["high-protein","fiber","low-calorie"] },
  'kadhi-pakora': { healthCategories: ["legume","fried"], tags: ["high-protein","fiber","high-fat"] },
  'kashmiri-biryani': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-calorie","high-protein"] },
  'kerala-egg-roast': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'kerala-fish-fry': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat"] },
  'keto-pizza-bowl': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein","low-calorie","fiber"] },
  'khar': { healthCategories: [], tags: ["low-calorie","fiber","healthy"] },
  'khoya-paneer': { healthCategories: ["lean-protein","unhealthy-fat"], tags: ["high-protein","high-fat","high-calorie","calcium"] },
  'kothimbir-vadi': { healthCategories: ["fried"], tags: ["high-fat","low-calorie","fiber"] },
  'kulfi': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'kuzhambu': { healthCategories: ["veg-fruit"], tags: ["fiber"] },
  'lebanese-lentil-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'lemon-coriander-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'lentil-feta-salad': { healthCategories: ["legume","veg-fruit"], tags: ["high-protein","fiber","low-calorie","healthy"] },
  'lentil-pasta-marinara': { healthCategories: ["refined-grain","legume"], tags: ["high-carb","high-protein","fiber","healthy"] },
  'loaded-veggie-nachos': { healthCategories: ["lean-protein"], tags: ["high-protein","fiber"] },
  'lobiya': { healthCategories: ["legume","veg-fruit"], tags: ["high-protein","fiber","healthy"] },
  'lucknowi-biryani': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-calorie","high-protein"] },
  'machher-jhol-bengali': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'malai-chaap': { healthCategories: ["lean-protein","unhealthy-fat"], tags: ["high-protein","high-fat"] },
  'manchow-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'mango-lassi': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'mango-nice-cream': { healthCategories: ["veg-fruit","unhealthy-fat"], tags: ["fiber","vitamins","low-calorie","high-fat"] },
  'mango-pineapple-banana-smoothie': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'manipuri-eromba': { healthCategories: ["lean-protein"], tags: ["high-protein","fiber","probiotic"] },
  'manipuri-kangsoi': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'masala-chai': { healthCategories: ["healthy-beverage"], tags: ["antioxidant","low-calorie"] },
  'masala-oats': { healthCategories: ["whole-grain","lean-protein"], tags: ["high-fiber","high-protein","low-calorie","fiber"] },
  'matar-mushroom': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber"] },
  'matar-paneer-wala': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber"] },
  'matar-pulao': { healthCategories: ["refined-grain","lean-protein","veg-fruit"], tags: ["high-carb","high-protein","fiber"] },
  'meghalaya-doh-khleh': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber","low-calorie","probiotic"] },
  'meghalaya-tun-jhol': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'methi-malai-matar': { healthCategories: ["lean-protein","veg-fruit","unhealthy-fat"], tags: ["high-protein","fiber","high-fat"] },
  'methi_chilla_north': { healthCategories: ["refined-grain","lean-protein","veg-fruit"], tags: ["high-carb","high-protein","fiber","low-calorie"] },
  'milk-oats-fusion': { healthCategories: ["healthy-beverage","dairy"], tags: ["high-protein","low-calorie"] },
  'mixed-vegetable-curry': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins"] },
  'mixed_veg_chilla_mh': { healthCategories: ["whole-grain","lean-protein"], tags: ["high-fiber","high-protein","low-calorie","fiber"] },
  'mizo-bai': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber"] },
  'mizo-vawksa': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'moong-dal-halwa': { healthCategories: ["dessert"], tags: ["high-sugar","indulgent"] },
  'moong_dal_chilla_south': { healthCategories: ["refined-grain","legume"], tags: ["high-carb","high-protein","fiber","low-calorie"] },
  'mulligatawny': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'murghi-na-farcha': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat"] },
  'mushroom-corn-masala': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber"] },
  'mushroom-do-pyaza': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber"] },
  'mushroom-matar': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber"] },
  'mushroom-pulao': { healthCategories: ["refined-grain","lean-protein","veg-fruit"], tags: ["high-carb","high-protein","fiber"] },
  'mushroom-toast': { healthCategories: ["refined-grain","lean-protein","veg-fruit"], tags: ["high-carb","high-protein","fiber","low-calorie"] },
  'mutton-biryani': { healthCategories: ["refined-grain","red-meat"], tags: ["high-carb","high-calorie","high-protein","high-fat"] },
  'mutton-curry': { healthCategories: ["red-meat"], tags: ["high-protein","high-fat","high-calorie"] },
  'mysore_dalia_dosa': { healthCategories: ["whole-grain","veg-fruit"], tags: ["high-fiber","fiber","low-calorie"] },
  'naatu-kozhi-rasam': { healthCategories: ["lean-protein"], tags: ["high-protein","low-calorie"] },
  'naga-axone-pork': { healthCategories: ["red-meat"], tags: ["high-protein","high-fat","high-calorie","probiotic"] },
  'naga-bamboo-shoot': { healthCategories: ["lean-protein"], tags: ["high-protein","fiber","probiotic"] },
  'nakham-bitchi': { healthCategories: ["lean-protein"], tags: ["high-protein","low-calorie"] },
  'nalli-nihari': { healthCategories: ["lean-protein","unhealthy-fat"], tags: ["high-protein","high-fat","high-calorie"] },
  'nandu-rasam': { healthCategories: ["lean-protein"], tags: ["high-protein","low-calorie"] },
  'nut-butter-banana-stackers': { healthCategories: ["lean-protein","healthy-fat"], tags: ["high-protein","healthy","low-calorie"] },
  'oat-milk-hot-chocolate': { healthCategories: ["dessert"], tags: ["high-sugar","calcium"] },
  'oats-poha': { healthCategories: ["whole-grain"], tags: ["high-fiber","low-calorie","fiber","healthy"] },
  'oats_sprouts_chilla': { healthCategories: ["whole-grain","lean-protein","veg-fruit"], tags: ["high-fiber","high-protein","fiber","low-calorie"] },
  'onion-pakora': { healthCategories: ["veg-fruit","fried"], tags: ["fiber","low-calorie","high-fat"] },
  'pachi-palusu': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'palak-ka-shorba': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'palak-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'paneer-achari': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'paneer-biryani': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'paneer-do-pyaza': { healthCategories: ["lean-protein","unhealthy-fat"], tags: ["high-protein","high-fat"] },
  'paneer-jalfrezi': { healthCategories: ["lean-protein"], tags: ["high-protein","fiber"] },
  'paneer-korma': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'paneer-pasanda': { healthCategories: ["lean-protein","unhealthy-fat"], tags: ["high-protein","high-fat","high-calorie"] },
  'paneer-pulao': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'paneer-roll': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'paneer_chilla': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'pappu-charu': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'parotta-kurma': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-calorie","high-protein"] },
  'paya-shorba': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'pea-protein-smoothie': { healthCategories: ["sugary-beverage"], tags: ["high-protein","low-calorie"] },
  'peach-milk': { healthCategories: ["healthy-beverage","dairy"], tags: ["low-calorie"] },
  'peanut-butter-cup-milkshake': { healthCategories: ["sugary-beverage","dairy"], tags: ["healthy","high-protein"] },
  'plain-lassi': { healthCategories: ["healthy-beverage","dairy"], tags: ["probiotic","high-protein","low-calorie"] },
  'poha_chilla_mh': { healthCategories: ["refined-grain"], tags: ["high-carb","low-calorie"] },
  'pongal': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-calorie","high-protein"] },
  'protein-coffee-smoothie': { healthCategories: ["sugary-beverage"], tags: ["high-protein","low-calorie"] },
  'protein-powder-mug-cake': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'pumpkin-sweet-potato-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'rabdi-faluda': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'rasam': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'raspberry-smoothie': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'red-lentil-dal': { healthCategories: ["legume"], tags: ["high-protein","fiber"] },
  'rice_chilla_cg': { healthCategories: ["refined-grain"], tags: ["high-carb","low-calorie"] },
  'rice_chilla_gujarat': { healthCategories: ["refined-grain"], tags: ["high-carb","low-calorie"] },
  'roasted-broccoli-potatoes': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins"] },
  'roasted-cauliflower-curry-sweet-potato': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins"] },
  'roasted-cauliflower-salad': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie","healthy"] },
  'sabudana-vada': { healthCategories: ["refined-grain","fried","starchy-veg"], tags: ["high-carb","high-fat"] },
  'schezwan-fried-rice': { healthCategories: ["refined-grain","fried"], tags: ["high-carb","high-fat"] },
  'schezwan-paneer': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'seekh-kebab': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat"] },
  'shammi-kebab': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat","low-calorie"] },
  'shev-puri': { healthCategories: ["refined-grain","fried"], tags: ["high-carb","high-fat","low-calorie"] },
  'shorshe-ilish': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'sikkimese-buckwheat': { healthCategories: ["whole-grain","fried"], tags: ["high-fiber","high-fat","low-calorie","fiber","healthy"] },
  'sindhi-aloo-tuk': { healthCategories: ["veg-fruit","fried"], tags: ["fiber","high-fat"] },
  'sindhi-kadhi': { healthCategories: ["legume","veg-fruit"], tags: ["high-protein","fiber"] },
  'sindhi-koki': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'singhara_chilla_vrat': { healthCategories: ["refined-grain"], tags: ["high-carb","low-calorie"] },
  'sourdough-grilled-cheese': { healthCategories: ["refined-grain","lean-protein","unhealthy-fat"], tags: ["high-carb","high-protein","high-fat"] },
  'soya-chaap': { healthCategories: ["lean-protein"], tags: ["high-protein","fiber"] },
  'spiced-hot-chocolate': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'spiced-masala-oats': { healthCategories: ["whole-grain","lean-protein"], tags: ["high-fiber","high-protein","low-calorie","fiber","healthy"] },
  'spring-rolls': { healthCategories: ["fried"], tags: ["high-fat","fiber"] },
  'strawberry-blueberry-pie': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'strawberry-cheesecake-cookies': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'strawberry-donuts': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'strawberry-juice': { healthCategories: ["healthy-beverage"], tags: ["low-calorie"] },
  'strawberry-smoothie-bowl': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'strawberry-yogurt': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber","low-calorie","healthy"] },
  'suji_chilla_north': { healthCategories: ["refined-grain","fried"], tags: ["high-carb","high-fat","low-calorie"] },
  'sweet-and-sour-chicken': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'sweet-and-sour-veg': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'sweet-corn-chicken-soup': { healthCategories: ["lean-protein"], tags: ["high-protein","low-calorie"] },
  'sweet-corn-veg-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'sweet-potato-breakfast-hash': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins"] },
  'sweet-sesame-noodles-tofu-broccoli': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'tahini-pasta': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'tamatar-ka-shorba': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'tandoori-chicken': { healthCategories: ["lean-protein"], tags: ["high-protein"] },
  'tofu-meatballs': { healthCategories: ["lean-protein","healthy-fat"], tags: ["high-protein"] },
  'tofu-pasta': { healthCategories: ["refined-grain","lean-protein","veg-fruit"], tags: ["high-carb","high-protein","fiber"] },
  'tomato-saar': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'tres-leches-cake-gluten-free': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'tripuri-biryani': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-calorie","high-protein"] },
  'tunday-kebab': { healthCategories: ["lean-protein","fried"], tags: ["high-protein","high-fat","low-calorie"] },
  'twice-baked-potatoes-broccoli-cheese': { healthCategories: ["lean-protein","veg-fruit","unhealthy-fat"], tags: ["high-protein","fiber","high-fat"] },
  'ulava-charu': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'uttapam-pizza': { healthCategories: ["refined-grain"], tags: ["high-carb"] },
  'veg-roll': { healthCategories: ["veg-fruit"], tags: ["fiber"] },
  'vegan-apple-muffins': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'vegan-biryani-cauliflower': { healthCategories: ["refined-grain","lean-protein","veg-fruit"], tags: ["high-carb","high-protein","fiber"] },
  'vegan-broccoli-salad': { healthCategories: ["veg-fruit","fried"], tags: ["fiber","vitamins","low-calorie","high-fat"] },
  'vegan-carrot-cake-cupcakes': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'vegan-chow-mein': { healthCategories: ["refined-grain","veg-fruit"], tags: ["high-carb","fiber"] },
  'vegan-egg-salad-sandwich': { healthCategories: ["refined-grain","lean-protein","veg-fruit"], tags: ["high-carb","high-protein","fiber","low-calorie"] },
  'vegan-french-toast-casserole': { healthCategories: ["refined-grain"], tags: ["high-carb","fiber"] },
  'vegan-fruit-cake': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'vegan-lemon-cupcakes': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'vegan-mug-cake': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'vegan-peanut-butter-cups': { healthCategories: ["lean-protein","healthy-fat"], tags: ["high-protein","healthy","low-calorie"] },
  'vegan-pineapple-upside-down-cake': { healthCategories: ["dessert"], tags: ["high-sugar"] },
  'vegan-potato-pancakes': { healthCategories: ["refined-grain","veg-fruit","fried"], tags: ["high-carb","fiber","high-fat"] },
  'vegan-rasta-pasta': { healthCategories: ["refined-grain","healthy-fat"], tags: ["high-carb","fiber"] },
  'vegan-smoothie-bowl': { healthCategories: ["sugary-beverage"], tags: ["low-calorie"] },
  'vegan-strawberry-milk': { healthCategories: ["healthy-beverage","dairy"], tags: ["low-calorie"] },
  'vegan-sushi-bowl': { healthCategories: ["refined-grain","lean-protein"], tags: ["high-carb","high-protein"] },
  'vegan-tomato-soup': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'vegan-vanilla-pudding': { healthCategories: ["dessert"], tags: ["high-sugar","calcium"] },
  'vegetable-oats-upma': { healthCategories: ["whole-grain","lean-protein","veg-fruit"], tags: ["high-fiber","high-protein","fiber","low-calorie","healthy"] },
  'vegetarian-fajita-bowl': { healthCategories: ["lean-protein","veg-fruit"], tags: ["high-protein","fiber"] },
  'vegetarian-taco-soup': { healthCategories: ["veg-fruit"], tags: ["fiber"] },
  'veggie-shawarma-tofu': { healthCategories: ["lean-protein"], tags: ["high-protein","fiber"] },
  'veggie-spaghetti-sauce': { healthCategories: ["veg-fruit"], tags: ["fiber","low-calorie"] },
  'watermelon-feta-mint-salad': { healthCategories: ["veg-fruit"], tags: ["fiber","vitamins","low-calorie"] },
  'wintermelon-milk-tea': { healthCategories: ["healthy-beverage","dairy"], tags: ["antioxidant","low-calorie"] },
  'yakhni': { healthCategories: ["lean-protein"], tags: ["high-protein","low-calorie"] },
};

export const COMPONENT_HEALTH_MAP: Record<string, { healthCategories: string[]; tags: string[] }> = {
  // ─── Rotis / Breads ─────────────────────────────────────────────────────────
  'Tandoori Roti': { healthCategories: ['whole-grain'], tags: ['high-fiber', 'healthy', 'low-fat'] },
  'Roti': { healthCategories: ['whole-grain'], tags: ['fiber'] },
  'Phulka': { healthCategories: ['whole-grain'], tags: ['fiber', 'low-fat'] },
  'Paratha': { healthCategories: ['whole-grain', 'fried'], tags: ['high-carb'] },
  'Laccha Paratha': { healthCategories: ['whole-grain', 'fried'], tags: ['high-carb', 'high-fat'] },
  'Bafla': { healthCategories: ['whole-grain'], tags: ['fiber'] },
  'Bhakri': { healthCategories: ['whole-grain'], tags: ['high-fiber', 'healthy'] },
  'Jolada Roti': { healthCategories: ['whole-grain'], tags: ['high-fiber', 'healthy'] },
  'Methi Thepla': { healthCategories: ['whole-grain', 'veg-fruit'], tags: ['fiber', 'iron'] },
  'Butter Naan': { healthCategories: ['refined-grain'], tags: ['high-carb', 'low-fiber'] },
  'Naan': { healthCategories: ['refined-grain'], tags: ['high-carb', 'low-fiber'] },
  'Garlic Naan': { healthCategories: ['refined-grain'], tags: ['high-carb'] },
  'Bhature': { healthCategories: ['refined-grain', 'fried'], tags: ['high-carb', 'high-fat'] },
  'Puri': { healthCategories: ['refined-grain', 'fried'], tags: ['high-carb', 'high-fat'] },
  'Bedmi Puri': { healthCategories: ['refined-grain', 'fried'], tags: ['high-carb', 'high-fat'] },
  'Luchi': { healthCategories: ['refined-grain', 'fried'], tags: ['high-carb', 'high-fat'] },
  'Kulcha': { healthCategories: ['refined-grain'], tags: ['high-carb'] },
  'White Bread': { healthCategories: ['refined-grain'], tags: ['high-carb', 'low-fiber'] },
  'Brown Bread': { healthCategories: ['whole-grain'], tags: ['high-fiber', 'healthy'] },
  'Milk Bread': { healthCategories: ['refined-grain'], tags: ['high-carb', 'low-fiber'] },

  // ─── Rice ───────────────────────────────────────────────────────────────────
  'Steamed Rice': { healthCategories: ['refined-grain'], tags: ['high-carb'] },
  'Jeera Rice': { healthCategories: ['refined-grain'], tags: ['high-carb'] },
  'Lemon Rice': { healthCategories: ['refined-grain'], tags: ['high-carb'] },
  'Pulao': { healthCategories: ['refined-grain'], tags: ['high-carb'] },
  'Sticky Rice': { healthCategories: ['refined-grain'], tags: ['high-carb'] },
  'Brown Rice': { healthCategories: ['whole-grain'], tags: ['high-fiber', 'healthy'] },
  'Fried Rice': { healthCategories: ['refined-grain', 'fried'], tags: ['high-carb', 'high-fat'] },
  'Biryani Rice': { healthCategories: ['refined-grain'], tags: ['high-carb'] },

  // ─── Gravies / Curries ──────────────────────────────────────────────────────
  'Curry': { healthCategories: ['healthy-fat'], tags: ['moderate'] },
  'Gravy': { healthCategories: ['healthy-fat'], tags: ['moderate'] },

  // ─── Sides ──────────────────────────────────────────────────────────────────
  'Salad': { healthCategories: ['veg-fruit'], tags: ['fiber', 'vitamins'] },
  'Kachumber Salad': { healthCategories: ['veg-fruit'], tags: ['fiber', 'vitamins', 'low-calorie'] },
  'Fruit Salad': { healthCategories: ['veg-fruit'], tags: ['fiber', 'vitamins', 'low-calorie'] },
  'Raita': { healthCategories: ['dairy'], tags: ['probiotic'] },
  'Curd': { healthCategories: ['dairy'], tags: ['probiotic'] },
  'Pickle': { healthCategories: ['veg-fruit'], tags: ['fermented'] },
  'Papad': { healthCategories: ['starchy-veg'], tags: ['moderate'] },
  'Green Chutney': { healthCategories: ['veg-fruit'], tags: ['vitamins'] },
  'Coconut Chutney': { healthCategories: ['healthy-fat', 'veg-fruit'], tags: ['healthy'] },
  'Sambhar': { healthCategories: ['legume', 'veg-fruit'], tags: ['high-protein', 'fiber'] },
  'Bun Maska': { healthCategories: ['healthy-fat'], tags: ['moderate'] },

  // ─── Beverages ──────────────────────────────────────────────────────────────
  'Chai': { healthCategories: ['healthy-beverage'], tags: ['moderate'] },
  'Filter Coffee': { healthCategories: ['healthy-beverage'], tags: ['antioxidant'] },
  'Chaas': { healthCategories: ['healthy-beverage', 'dairy'], tags: ['probiotic', 'healthy'] },
  'Lassi': { healthCategories: ['healthy-beverage', 'dairy'], tags: ['probiotic'] },
  'Buttermilk': { healthCategories: ['healthy-beverage', 'dairy'], tags: ['probiotic', 'healthy'] },
  'Water': { healthCategories: ['healthy-beverage'], tags: ['healthy'] },
  'Orange Juice': { healthCategories: ['veg-fruit'], tags: ['vitamins', 'low-calorie'] },

  // ─── Dessert ────────────────────────────────────────────────────────────────
  'Gulab Jamun': { healthCategories: ['dessert'], tags: ['high-sugar', 'indulgent'] },
  'Rasgulla': { healthCategories: ['dessert'], tags: ['high-sugar'] },
  'Kheer': { healthCategories: ['dessert', 'dairy'], tags: ['high-sugar'] },
  'Ice Cream': { healthCategories: ['dessert', 'dairy'], tags: ['high-sugar', 'indulgent'] },
};
